export const PATH_API = {
    login: "Users/authenticate",
    release_dashboard: "Dashboard/release-dashboard",
    requirement_dashboard: "Dashboard/requirement-dashboard",
    test_case_dashboard: "Dashboard/test-case-dashboard",
    defect_dashboard: "Dashboard/defect-dashboard",
    defect_trend_dashboard: "Dashboard/defect-trend-dashboard",
    batches_dashboard: "Dashboard/batch-workflow-dashboard",
    batch_test_daily_dashboard: "Dashboard/batch-test-daily-dashboard",
    get_requirement_grid_chart: "RequirementRegister/get-requirement-grid-chart",
    get_requirement_detail: "Requirement/get-requirement-detail",
    get_requirement_type: "Requirement/get-requirement-type",
    get_iso_classification: "Requirement/get-iso-classification",
    business_importance: "BusinessImportance",
    get_sub_classification: "Requirement/get-sub-classification",
    create_requirement: "Requirement/create-requirement",
    get_new_id: "Common/get-new-id",
    delete_requirement: "Requirement/delete-requirement",
    get_mini_dashboard: "Requirement/get-mini-dashboard",
    get_issue_status: "Requirement/get-issue-status",
    get_execution_status: "Requirement/get-execution-status-v2",
    get_histories: "Requirement/get-histories",
};
export const ROUTER = {
    dashboard: "/dashboard",
    release: "/release",
    requirement: "/requirement",
    login: "/login",
};
export const APIUrl = "http://api.pinnacle-qa.server2div3.pgtest.co/api/";